### ISSUE TITLE
How about the processed datasets?

### ISSUE THREAD

**Issue by A11en0** [penfever/ArcheType#3]
Hi, thanks for your great job. I am kindly request if you could share the processed dataset that you used for your project. For example, the SOTAB-27 you named in your paper simplifies the original SOTAB into 27 distinct labels.

**Comment by A11en0** [comment]
How can I find the `flan-t5-xxl-zs-shortprompt` model checkpoint?

**Comment by penfever** [comment]
Hi! The SOTAB-27 and SOTAB-91 benchmarks were constructed from the SOTAB dataset. The SOTAB train, validation and test files, as well as instructions for their extraction and use, can be acquired via their website. (http://webdatacommons.org/structureddata/sotab/)

Once you have downloaded and extracted the SOTAB dataset, you need only direct ArcheType to the correct data path and specify the label set you wish to apply as a command line argument (E.G., --label_set="SOTAB-91")

**Comment by A11en0** [comment]
I apologize for the oversight. Thank you for your guidance!
