### ISSUE TITLE
Could you please upload the checkpoint of fine-tuned ArcheType?

### ISSUE THREAD

**Issue by A11en0** [penfever/ArcheType#4]
Thanks for your great job. It's impressive that introduce such a new method to the community. Could you please upload the fine-tuned checkpoints.

**Comment by penfever** [comment]
Happy to help!  Unfortunately, the fine-tuned results reported in Table 3 of our paper were achieved using a fine-tuned LLAMA-7B checkpoint, and we are not allowed to redistribute the LLAMA-1 weights. However, in a future update, we plan to re-run the experiments in table 3 using LLAMA-2 weights and post them to Huggingface; when this is done, we will update the readme accordingly.

**Comment by A11en0** [comment]
Thanks, Hope you get better results on LLaMA2.
