### ISSUE TITLE
NameError: name 'addl_labels' is not defined

### ISSUE THREAD

**Issue by jamesford007** [penfever/ArcheType#6]
I am attempting to run a zero-shot CTA on for my own custom data and labels:

```
python src/run.py --model_name="llama" --save_path="test_run/results.json" --input_files="data/Test" --input_labels="skip-eval" --label_set="custom" --custom-labels type place number date size description--method ans_contains_gt gt_contains_ans resample --response
```
I receive the following error:
```
"ArcheType\src\model.py", line 171, in get_model_resp 
lsd['label_set'] = lsd['label_set'] + addl_labels
NameError: name 'addl_labels' is not defined
```
As suggested by the error  'addl_labels' is called in _model.py_ but is not defined

**Comment by A11en0** [comment]
Could you re-produce the results on the benchmark datasets?

**Comment by penfever** [comment]
Thanks for bringing this to our attention --we have just issued a patch which should hopefully resolve your issue. Please feel free to re-open the issue if you encounter another problem.
